server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/printshop
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:huynhtannha2003@gmail.com}
    password: ${MAIL_PASSWORD:cgah urjw psal rrvk}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

file:
  upload-dir: ./uploads

jwt:
  secret: 123456789101234567891012345678910123456789101234567891012345678910
  expiration: 86400000
  refresh-token:
    expiration: 604800000

app:
  email:
    from: ${MAIL_FROM:noreply@printshop.com}

# ============================
# VNPay Sandbox Configuration
# ============================

vnpay:
  tmnCode: R2A9HETV
  hashSecret: 1PWAY5NNP74M2EPGESFX302ME9FX3QX2
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl:  https://temptingly-spleeniest-latonia.ngrok-free.dev/api/vnpay/return
  ipnUrl:  https://temptingly-spleeniest-latonia.ngrok-free.dev/api/vnpay/ipn
